name: 'action-commit-store'
description: 'action using a commit comment as a key value store'
author: 'Jonas Strassel'

branding:
  color: orange
  icon: database

inputs:
  storage-commit-sha:
    required: true
    description: 'commit to be used as storage'
  key: 
    required: true
    description: 'key to store in'
  value:
    required: false
    description: 'value to store. returns current value if not set.'
  token:
    required: false
    description: 'set the secret.GITHUB_TOKEN either via with or env. ref. https://github.com/octokit/auth-action.js#createactionauth'
  encryption-key:
    required: false
    description: 'optionally provide a 32-character-long secret used for end-to-end encryption of your values'

outputs:
  updated:
    description: 'true if value has changed'
  encrypted:
    description: 'true if the state is stored encrypted'
  value:
    description: 'value for given key'

runs:
  using: 'node16'
  main: 'dist/index.js'
